### ISSUE TITLE
v1.3.1 - PocketGo2 v1 / PG2v1 Won't Shutdown

### ISSUE THREAD

**Issue by jenstyler** [eduardofilo/RG350_adam_image#125]
Newly installed fresh SD cards. No ROMs, apps, or anything. Fresh install of v1.3.1 using etcher to a 32gb primary card. I hit start > shutdown and goes through the image unloading process, the screen goes black and the green LED turns off. Few seconds later it boots back up without touching anything.

**Comment by eduardofilo** [comment]
Already commented in issue #7

**Comment by eduardofilo** [comment]
The @esmith13 's workaround in README:

https://github.com/eduardofilo/RG350_adam_image#console-cannot-be-powered-off-pg2v1
