### ISSUE TITLE
Overclocking is not working

### ISSUE THREAD

**Issue by m45t3r** [eduardofilo/RG350_adam_image#174]
On 1.3.1, overclocking is not effectively working. Setting any entry with `Overclock: yes` will result on it showing as `-` instead of `+`, and I can't see any difference in performance.

I think the reason for this is the `config.ini` from `simplemenu`. Instead of having a `overclock_speed` entry like [this](https://github.com/fgl82/simplemenu/blob/main/simplemenu/output/OD-BETA/config/config.ini#L37-L40
), it has a `overclock_low_speed` and `overclock_high_speed` instead (maybe this was caused by the `simplemenu` beta from 1.3?).

Adding `overclock_speed` entry on `config.ini` manually fixes this. The entry after setting overclock show as `+`, and I also see some performance improvements.

**Comment by eduardofilo** [comment]
Totally right. Thanks for the finding. I will fix in 1.4.

**Comment by eduardofilo** [comment]
Solved in release v1.4.
