### ISSUE TITLE
Post 1.3.1 updates

### ISSUE THREAD

**Issue by m45t3r** [eduardofilo/RG350_adam_image#175]
This is just some updates that I did manually to my 1.3.1 setup that brings some visible improvements:

- Update `pcsx4all` to the latest version ([1.5](https://github.com/jdgleaver/RG350_pcsx4all/releases/tag/1.5)). I think 1.3.1 ships with `pcsx4all` version 1.4.1. Fixes an issue with analog input in Final Fantasy IX (that I am currently playing)
- Update `simplemenu` to version [10.3](https://github.com/fgl82/simplemenu/releases/tag/10.3) (this is not the latest, however the 10.3.1 was not released for RG350). This fixes a cosmetic issue when the terminal output sometimes shows when entering/exiting an app.
- Update RetroArch to whatever is the latest release here: https://github.com/eduardofilo/RG350_auto_ra_installer/releases

**Comment by eduardofilo** [comment]
Hi.

The two last points were included in 1.4 Adam's release, but I was not aware of the evolution of PCSX4All. Thanks for the information. I will include it too.

**Comment by SuperBadger77** [comment]
How far aways is v1.4?

**Comment by eduardofilo** [comment]
> How far aways is v1.4?

Is in testing phase. Do you want to test it?

**Comment by SuperBadger77** [comment]
> > How far aways is v1.4?
> 
> @SuperBadger77 Is in testing phase. Do you want to test it?

Sure! Didn’t realise it was in test phase. Where do I start and is there a change log? 😀

**Comment by eduardofilo** [comment]
@SuperBadger77 I have opened [this discussion](https://github.com/eduardofilo/RG350_adam_image/discussions/177) with the details. Thanks for your interest.

**Comment by eduardofilo** [comment]
Solved in release v1.4.
