### ISSUE TITLE
Bard Storyteller 0.10

### ISSUE THREAD

**Issue by jalidi** [eduardofilo/RG350_adam_image#185]
First of all, thank you for the hard work on this image leading up to Adam 1.4.
My problem is opening the Bard Storyteller v0.10 OPK file on the RG350M after flashing the latest image.
I'm likely in the minority of users who want an ebook reader on this device but I do enjoy reading txt files when I'm not gaming.
It used to work on the original image that I had on this prior to using Adam but now it simply crashes out. 
Neither SimpleMenu or Open Dingux work with the OPK file in the /apps directory of either my internal or external card.
I suppose, worse comes to worse, I can just flash the original image onto another microsd for the sole purpose of Bard. 
But just wondering if there's an easy fix. 
Thank you very much!
-Jalidi.

**Comment by eduardofilo** [comment]
Hi.
I have downloaded this version:
https://github.com/SeongGino/RetroGame350-AppRepo/raw/master/Applications/Bard_0.10.0.opk

It does indeed give an error for using an incorrect fixed path in a containing script.
I have adjusted that route and it already opens, although it is easy to close when pressing some controls. Surely it would be necessary to recompile the code with the ODb toolchain.

[Bard_0.10.0.zip](https://github.com/eduardofilo/RG350_adam_image/files/8036320/Bard_0.10.0.zip)
