### ISSUE TITLE
Dinput not working on 1.4

### ISSUE THREAD

**Issue by chunguifriki** [eduardofilo/RG350_adam_image#188]
Hi,
I am testing a DualShock controller connected via usb to the OTG port. The console is RG350M and Adam Image is version 1.4 .
So far, the DS4 is not recognised at all. I tried PSX games, GBA and GBC with retroarch. In retroarch none of the buttons nor joysticks are detected when setting a new input.
Also, the menu won't recognise the controller.

When using the "original" SD card with anbernic opendingux the DS4 controller is fully usable.

I don't know if this is a bug or is not compatible. I've read online that DS4 via USB is a Dinput controller; I don't have any other Dinput controller to check.

PS: I also tested the Xbox 360 wired usb controller, but it won't work on neither Adam Image 1.4 or anbernic opendingux (maybe helpful).

Thanks for the Adam Image, it is amazing!

**Comment by eduardofilo** [comment]
I'm sorry, but the support of devices is not part of the work I do with the image. I only install system and programs, which are what support the hardware.
