### ISSUE TITLE
pls put in your wiki for CPS2  and PS1 file format issues

### ISSUE THREAD

**Issue by cyberazi** [eduardofilo/RG350_adam_image#19]
Take note that CPS2 roms placed in CPS foleder u need to manually assign the dore. Or can we seperate cps1 and 2?

Also note that for PS1 rom in "Bin and cue" format when zipp up together will not work. However ISO files when zipped and compressed will work

**Comment by eduardofilo** [comment]
Comments about these issues included in v1.2
