### ISSUE TITLE
Dead loop when start rg280 is back in 1.4

### ISSUE THREAD

**Issue by K1w3** [eduardofilo/RG350_adam_image#198]
After few days of working good dead loop are appering when starting device. It is rg280v

**Comment by K1w3** [comment]
Yes i was changing video filter for gameboy in retroarch settings and using overrides. Thank you for your reference it helps :)

**Comment by eduardofilo** [comment]
If it was doing overrides, then the reboot loop shouldn't be related to SimpleMenu. If it still happens, make a video so we can continue investigating. If it has already been solved, tell us how you did it, please.

**Comment by K1w3** [comment]
Now i flash another sd card with v 1.4 and make the same changes as before. If dead loop appear i would make video. Last card was the one that came with device (has been formated).

**Comment by K1w3** [comment]
With last sd card reference from neilswan80  was helpful but than white horisontal stripes apear on screen and i was assuming that sd card was fault. Because of that it has been formated

**Comment by eduardofilo** [comment]
In that case, I'll close the issue and if it happens again, try the procedure that @neilswann80 told you about. If it doesn't work, send us a video and we'll look the issue again.

**Comment by K1w3** [comment]
Ok, thanks
