### ISSUE TITLE
Source / Contributing?

### ISSUE THREAD

**Issue by john-parton** [eduardofilo/RG350_adam_image#2]
How is this image actually built? Is the source available so that I can tweak things or contribute?

Thanks.

**Comment by eduardofilo** [comment]
You are right.
I made the image basically by hand installing these pieces:

1. Stock firmware of RG280V.
2. OpenDingux Beta update.
3. RetroArch installer with [this installer](https://github.com/eduardofilo/RG350_auto_ra_installer) and [this configuration](https://github.com/eduardofilo/RG350_auto_ra_installer/blob/master/adam.csv).
4. SimpleMenu.
5. Some standalone emulators and apps like Commander and [Py Backup](https://github.com/eduardofilo/RG350_py_backup).
6. xMAME fixing file permissions and installing [this settings interface](https://github.com/eduardofilo/RG350_xmame_sm_bridge).
7. Finally I integrated some scripts to expand SD1 partition and to create folder scaffolding on SD2.

I plan to develop some scripts to facilitate the publishing of updates. When I have organized it a bit, I will publish all in this repo together with the files of points 3 to 7 so you can reproduce my steps.

**Comment by john-parton** [comment]
Sounds good.

I believe it's possible to directly build OpenDingux Beta images using the buildroot, versus building an update OPK.

**Comment by eduardofilo** [comment]
To insert all the pieces in Buildroot would take a long time, at least with my skills. It would be interesting, but I definitely don't have that much time.

**Comment by anderbubble** [comment]
I would also be interested to contribute. @john-parton, do you have a pointer to documentation for how to build od-beta with buildroot? I've found it difficult to find documentation on its build process, too.

**Comment by john-parton** [comment]
@anderbubble 

Use a Linux machine or virtual machine for building. (Or WSL if you really want.)

Clone this repo: https://github.com/OpenDingux/buildroot

Run

`CONFIG=gcw0 ./rebuild.sh`

it will build everything and output the new OPK.

**Comment by anderbubble** [comment]
@john-parton ah, fair enough. I was hoping to be able to build something that could entirely replace the original image from scratch, rather than something that would have to be applied to it; but if we could get @eduardofilo's changes rolled into an OPK that'd be a win on its own.

@eduardofilo if you could provide some more specific detail about your steps, I would be interested to try to help modify the buildroot. The scripts you're already talking about would probably be precisely that. :)

**Comment by eduardofilo** [comment]
I've already figured out how I'm going to do the automated build system for the image, but it will take a while to assemble. But it will be with scripts, not with Buildroot.

**Comment by john-parton** [comment]
I'll see if I can run the build script on my machine. If I need to make any modifications, I'll submit a pull request.

**Comment by john-parton** [comment]
Are there instructions on how to build P2?

**Comment by eduardofilo** [comment]
I don't understand what you mean, sorry.

**Comment by john-parton** [comment]
Any updates on how to build an image?

I want to build a version of this for the RS90. https://opendingux.net/opendingux/2020/10/04/opendingux-release-20201004.html

**Comment by eduardofilo** [comment]
I started the work but I still have a long way to go.

**Comment by eduardofilo** [comment]
I can finally consider this issue closed. As of commit f600bfd2e5c494ae5426c788c08db79a7c902595 all the content of the image is inside this repository, so it can be built from source without relying on a previous installation on a microSD.
Now the Readme in the repository focuses on the build of the image. All documentation on the use of the images provided in the releases has been moved to the wiki section of the repository.
