### ISSUE TITLE
Can't get VBEmu to work..

### ISSUE THREAD

**Issue by kjettern** [eduardofilo/RG350_adam_image#205]
Hello.
I'm trying to get VBEmu to work, but when I start av game, the game quits right back to SimpleMenu. 
I don't think there was a problem on v.1.3.1. 
Is it just me or is this a common problem?

**Comment by neilswann80** [comment]
Strange, I'm not getting that issue. I'm playing on an RG350M.  I think in another post you mentioned you're on a 280V?  Same symptoms for every game you try?  Could you try running one of the games from here: https://archive.org/details/VirtualBoyROMS
to check it's not a corrupted or unsupported game file?

**Comment by kjettern** [comment]
Yes I'm on 280V. Same for every rom and it works when I choose retroarch instead. So roms are good. I installed 1.4.1 from scratch and did not update. Could that be the difference?

**Comment by kjettern** [comment]
Logs are saying:
Starting VB-boyemu
Can't load ROM
Could not load ROM in memory

**Comment by eduardofilo** [comment]
It must be a problem with the ROMs. Only the first line of the log should appear as you can see.
![screenshot001](https://user-images.githubusercontent.com/2923728/154140566-d4f5713a-524d-4d3d-a915-a936cd9dcc10.png)

**Comment by eduardofilo** [comment]
I have them in `.vb` format.
Maybe yours are compressed.

**Comment by kjettern** [comment]
Mine are zip. That could be it. I will check it tomorrow.

**Comment by kjettern** [comment]
.zip was the problem. Now it's working with .vb. Thank you for all the help!

**Comment by eduardofilo** [comment]
zip is there for RA compatibility only. I'm glad it wasn't anything serious.
