### ISSUE TITLE
GBA roms duplicate

### ISSUE THREAD

**Issue by Nathan-Samson** [eduardofilo/RG350_adam_image#21]
Whenever I start any of my GBA ROMs for the first time, they create a duplicate copy. These copies work, and don't create copies of their own. (On RG350M).

**Comment by a-dekker** [comment]
Do you happen to have your ROM's in zip format?
If so, retroarch extracts the zip file. The default retroarch setting of the adam image is to use the current directory as cache directory. If it does not get cleaned up, you end up with an extracted and still zipped version. I ended up with changing the cache directory to /tmp. This way the extracted image will not interfere and also be gone after a shutdown or reboot.

**Comment by eduardofilo** [comment]
Great workaround @a-dekker. I'm going to apply that change to the image. Thank you very much.

**Comment by Nathan-Samson** [comment]
Yeah, that seems to be the issue here. Thanks, I'll try the fix.

**Comment by eduardofilo** [comment]
Included in v1.2
