### ISSUE TITLE
Alias entry for "yumefuda" causes crash when "Tidy rom names" is enabled

### ISSUE THREAD

**Issue by vonmillhausen** [eduardofilo/RG350_adam_image#210]
In the main `alias.txt` included in Adam 1.4.1's Simplemenu build, the entry on line 7140 reads:

```
yumefuda=(Medal) Yumefuda [BET]
```

When the "Tidy rom names" Simplemenu option is enabled (which it is by default), this causes everything from the first `(` character onwards in the rom name to be stripped. In the case of this arcade game, as the aliased name begins with a `(` it creates a blank entry in the game list, and scrolling over it crashes Simplemenu. Technically this is an up-stream Simplemenu bug (which I've also filed here: https://github.com/fgl82/simplemenu/issues/199), but it can be worked-around in Adam by altering this line in the alias file (it's the only one that begins with at `(`).

**Comment by neilswann80** [comment]
@vonmillhausen Nice catch!

FYI... if you want the alias name to show up as it should in SimpleMenu, change it to:
`yumefuda=(Medal)() Yumefuda [BET]`

SimpleMenu should then only strip out the second set of brackets.

**Comment by eduardofilo** [comment]
Thanks for reporting @vonmillhausen. @neilswann80 has already prepared a patch for the next revision.
