### ISSUE TITLE
RNDIS Not Working on 1.4/1.4.1, Working on 1.3 (RG300X, RG280V)

### ISSUE THREAD

**Issue by yossariano** [eduardofilo/RG350_adam_image#212]
This is a bit of an odd one since this clearly works for other people, but I've tried on both an RG300X and an RG280V and both experience the following issue. On versions 1.4 and 1.4.1, I cannot connect to either device using

```
ssh od@10.1.1.2
```

However, I flashed Adam image 1.3 onto both the devices, and it is working perfectly fine there, without changing anything on my PC side. Same command on both (using a password as well as after turning the password off with the "Password" app).

I figure it must be something on my end since I haven't found any mention of this when I looked for it, but I'd appreciate any help with advice on what I can look into to fix it. I would definitely like to be able to update to later versions, and ssh over usb is a must-have for me since I like to keep my save files in sync with my PC. I can prep an sd card with 1.4.1 and one with 1.3 and can run any commands that might help troubleshoot this issue.

**Comment by neilswann80** [comment]
I've tested ssh from a Linux terminal via ECM and from Windows PowerShell via RNDIS and both are working for me.  I'm on Adam v1.4.1 on an RG350M.

Do you have access to a Linux PC to test if you can get an ssh connections through ECM?  Might be useful to know if all USB networking is affected or solely RNDIS.

Also on the WIKI [here](https://github.com/eduardofilo/RG350_adam_image#system-access) it does say:
`If you want to change or disable it, you must use the Password application (only accessible from GMenu2X in the settings section)`
This may now me old information as the Password application is available in SimpleMenu, but perhaps try dropping out of SM and into GMenu2X and try clearing the password from there?

**Comment by yossariano** [comment]
Hmm- I just tested 1.4.1 again on a new SD card and it worked fine. I must have done something incorrect earlier when I was initially testing. Going to close this out- sorry for the churn!
