### ISSUE TITLE
HDMI out doesn't work on RG350P

### ISSUE THREAD

**Issue by RaphRob** [eduardofilo/RG350_adam_image#215]
I try it with 1.3, 1.3.1, 1.4, 1.4.1, 1.4.2 and none can output video on my RG350P. The HDMI Beta patch on OG Firmware can.

**Comment by neilswann80** [comment]
It's working for me on my RG350M.
I'd advise connecting and disconnecting the HDMI cable with your device powered off.

Did you chose the option to enable HDMI and reboot from the SimpleMenu main menu? 
I.e. menu accessed by pressing `START`

For me the display is initially green-ish, but loading and closing any game fixes that.  I don't get any sound over HDMI to my TV, but I get sound from my device ok

**Comment by RaphRob** [comment]
Yes, I use START on SimpleMenu and HDMI (and it reboot). I don't see anything showing "enable" or something like that.

On my RG350P, I select HDMI (in settings on SimpleMenu) and it reboot directly on SimpleMenu without the screen turning off or the HDMI out on.

On my RG350 (OG), after selecting HDMI the same way, The screen is turning black but nothing out of the RG350. I need to reboot the RG350 with the HDMI disconnect to get something back on the console screen.

**Comment by neilswann80** [comment]
After I select HDMI and press `A` my device reboots.  Like you say, the device screen stays black, but I have output on my TV.

**Comment by RaphRob** [comment]
On my RG350 OG that what I get, whitout the TV output.

But on RG350P, I just get nothing... It just reboot whitout doing anything.

Is there anybody who has tried on one of this 2 models ?

**Comment by neilswann80** [comment]
Hopefully someone else with the exact same models as you will reply and offer a suggestion.

In the meantime, perhaps try clearing your last SimpleMenu save state by deleting the file:
`/media/data/local/home/.simplemenu/last_state.sav`
and trying again?

**Comment by RaphRob** [comment]
Thank you for your help.
I try your last solution but no change.

**Comment by eduardofilo** [comment]
I have been trying with RG350/P and RG350M kernels and the HDMI out works on both. Well it works as always with sync problems in interphase screens, but it works as expected. It have to be an issue related to your device. If you say that it works with other firmwares, I understand that your machine may have some kind of marginality, as it works with most of them. In any case, if there is a problem with the implementation of the HDMI output, please note that we don't develop that part of the image here. We just integrate that and other parts to produce a whole. There are things that can malfunction because of misconfiguration, but I understand that this issue does not depend on that.

We can try to help you solve your problem, but as long as it's not a cable problem, I don't think there's much more we can do.

**Comment by eduardofilo** [comment]
I forgot to clarify that it is not necessary to use the entry in the SimpleMenu settings menu. Just switch on the console with the cable connected beforehand, i.e. with the console switched off.

**Comment by RaphRob** [comment]
I understand. It's too bad that both of my units RG350 and P doesn't output HDMI.
Thanks a lot for your help.
Maybe I do something wrong ? Just to be sure:
1) I flash 1.4.2 on a sd card
2) I run the script to choose the model
3) I insert the sd in the console
4) I plug the HDMI cable
5) I boot the console

Am I missing something ?

Again thanks a lot for your help and all your work.

**Comment by neilswann80** [comment]
> I forgot to clarify that it is not necessary to use the entry in the SimpleMenu settings menu. Just switch on the console with the cable connected beforehand, i.e. with the console switched off.

On my RG350M if I boot the device with the HDMI connected I get no output, I have to choose the `enable and reboot` option (via SimpleMenu `START`) to then get video output.

@RaphRob the steps you describe sound totally correct.  Sorry you're experiencing this, losing HDMI out is a pain as it's a great feature.
Are you flashing to the same microsd every time?  If so, could you try using a different microsd?  (clutching at straws now with this suggestion)

**Comment by eduardofilo** [comment]
Well again it's weird because apart from the tests I did yesterday, several RG350M users confirm to me that it works without using the SimpleMenu menu. Also think that the HDMI output functionality is part of OpenDingux and should work whether SimpleMenu is installed or not. I don't know, maybe it depends on the HDMI version supported by the console and the TV.
In any case as I commented, there is not much I can do about it other than test different scenarios and try to draw conclusions about how it works.
Sorry.

**Comment by eduardofilo** [comment]
> One more (clutching at straws) suggestion. Are you using `Balena Etcher` to flash the microsd? Could you try the flash process from another PC? I've had issues where my PC seems not to flash images well (for both my RG350M and my Pinephone) but my laptop flashes images consistently well.

Do you own a Pinephone? You rocks :-)

**Comment by RaphRob** [comment]
Ok, I try:
- Multiple SD card
- Multiple hdmi cable
- Multiple Screen
- I use Balena Etcher

I only have one laptop.
But,
I install ODbeta only, and same result. No HDMI out. So It's not adam fault.
Maybe its just my unit. I will go back to OD stock to get HDMI and wait for an update maybe one day ^^

Thanks a lot for all your help.

**Comment by RaphRob** [comment]
Oh and I didn't found any "HDMI advanced standard" option on the differents screen. Sorry.

**Comment by neilswann80** [comment]
>I will go back to OD stock to get HDMI and wait for an update maybe one day ^^
> 
> Thanks a lot for all your help.

Fingers crossed an update to OD that fixes this is just around the corner for you.

**Comment by neilswann80** [comment]
> @neilswann80 Do you own a Pinephone? You rocks :-)

Yes I do!  :)
I have a Pinephone and a Pinephone keyboard case... and I'm tempted to get a Pinephone Pro.  I also have a Pinecil (soldering iron) which I also recommend.  The Pinecil will run off a PD powerbank which is ideal for me as I'm often working in places power sockets aren't always available.

The Pinphone is mainly a toy for tinkering with (for me) at the moment.  It's still a little too unstable for daily use.  I do have a OnePlus One running UBPorts however which is my daily driver.  I'm trying to move all my main devices across to the Linux platform currently, relegating Windows to just a gaming environment.

**Comment by eduardofilo** [comment]
> > @neilswann80 Do you own a Pinephone? You rocks :-)
> 
> @eduardofilo - Yes I do! :) I have a Pinephone and recently purchased the new Pinephone keyboard case for it... I'm tempted to get a Pinephone Pro in the near future.
> 
> I also have a Pinecil (soldering iron) which I highly recommend. The Pinecil will run off a PD powerbank which is ideal for me as I'm often working in places power sockets aren't functioning or aren't available.
> 
> The Pinephone is mainly a toy for tinkering with (for me) at least for the moment, it's still a little too unstable for daily use. I do have a OnePlus One running UBPorts which is my current daily driver and I may "upgrade" this to a Pixel 3a (also running UBPorts) soon so I can make use of Halium 9 and Waydroid; being able to run android apps from Linux will be very useful. I've tried Anbox on my current device, but found it too glitchy.
> 
> I'm in the process of moving all my main devices across to the Linux platform currently, relegating Windows to just a gaming environment. I'm trying to avoid Microsoft/Apple/Google software wherever possible.

I also love pinecil: http://apuntes.eduardofilo.es/ingenieria/herramientas.html#pinecil

I know that the Pinephone is considered a development phone. That is why you rocks :-)
I also use Oneplus phones. In fact I still have the One and have been installing UBPorts on it from time to time to see how it evolves, but I still haven't dared to abandon Android. I would like to move on to the distributions being developed on Pinephone as soon as possible.

**Comment by neilswann80** [comment]
You've got many cool and interesting projects on the go!  So you rocks!  

What project are you finding most interesting and enjoyable currently?

**Comment by eduardofilo** [comment]
This one: https://apuntes.eduardofilo.es/retro-emulacion/z80-computer.html

I plan to make a mix of those projects to build my own Z80 computer. With modules I want to make it compatible with ZX Spectrum and MSX. We'd better find another channel of communication, we're going to make RaphBob dizzy.

Have you Discord or Telegram user? If yes, send me the ID to the email account associated to my Github account.
