### ISSUE TITLE
Cheatsheet link not working

### ISSUE THREAD

**Issue by SuperBadger77** [eduardofilo/RG350_adam_image#217]
The cheat sheet link isn't working - get a 404: https://github.com/eduardofilo/RG350_adam_image/blob/master/resources/Adam.Image.Cheatsheet.v1.3.pdf

However if you go to https://github.com/eduardofilo/RG350_adam_image/tree/master/resources you can see it is there. Think the link just needs updating. Also not sure if it needs updating for any of the smaller updates to bring it inline with 1.4.2.

**Comment by neilswann80** [comment]
@SuperBadger77 thanks for reporting.  I've created [PRs](https://github.com/eduardofilo/RG350_adam_image/pull/218) for @eduardofilo that will fix the broken link.
