### ISSUE TITLE
Having issues with the analog stick on PG2v2

### ISSUE THREAD

**Issue by Stories8106** [eduardofilo/RG350_adam_image#22]
I have the bottom reset button, so I think its PG2v2. 

The analog is detecting, but registering slightly up and to the left of center. 

The analog registers fine on "out of the box" firmware and my backup of it. I haven't tried any other images.

Tried the using the pg2test.opk from another issue, and same result.  Its like it's fluttering around the .26 range.  I attached a picture, but thats from the original RG350 testing opk on the image.

Unfortunately, this is rendering the entire image useless, since every emulator is registering the analog as dpad inputs.
![PXL_20210902_014945277](https://user-images.githubusercontent.com/26497422/131898484-5e6d8fac-7feb-41b2-8938-b9a165621356.jpg)

**Comment by eduardofilo** [comment]
The last image indicated that the PG2v2 used the RG350 kernel (the third in the selection script). It is compatible for the most part, but not 100%. Then I learned that the kernel that I listed fifth as suitable for PG2v1 was actually the correct one for PG2v2. In the next release I will reorganize that topic, but in the meantime try to select kernel number 5 (no need to flash again, just rerun the select_kernel.bat script). If you do, try again and tell me if the stick issues have been fixed, please.

**Comment by Stories8106** [comment]
Tried to select kernel #5, same issue.  I did not reflash, but will tonight just in case.

**Comment by Stories8106** [comment]
Any updates on this?

**Comment by eduardofilo** [comment]
I'm sorry. I only can update the base system hoping that it incorporates the solution to your problem. I don't have that machine, so I can't even test the problem to try to help the base system developers. I was talking with @Ninoh-FOX about this issue and he comment me that "It seems as if the stick has more sensitivity in beta than in stock", so your stick probably has a defect that was hidden in stock due to the lower sensitivity in that system, that is, because it has more tolerance to the neutral position.

**Comment by Stories8106** [comment]
Might be relevant, but issue #7 : 

_"Your latest image (v1.2e) boots and operates fine in general.
Shutdown works if you correct the system clock via gmenu2x first. It reboots instead of shutting down if the year is drastically off in either direction.
Brightness was barely visible on first boot. Easily fixed by exiting to gmenu2x and using the power+DPad shortcut for brightness.
Analog stick is not recognized, but as with previous images, using @Ninoh-FOX boot files instead of what is included with your image the analog works fine.
Image seems very stable after a few hours of play, regardless of which boot files are used. I am quite impressed with how the PG2v1 performs with your software!"_

So, would it possible to do this and try?  I'm not sure what files would I would need or how to do it.  I'm no dummy, but I don't know linux or the infrastructure of your image. Can you walk me through it?

**Comment by eduardofilo** [comment]
But in that issue #7 the conversation and the files that Ninoh-FOX prepared were for PG2 v1, not v2 like in your case. So the files won't work for you.

**Comment by Stories8106** [comment]
Could we ask him for a PG2v2 kernel and make a similar attempt?

**Comment by eduardofilo** [comment]
Well, sure he is capable of generating a perfectly calibrated kernel for your stick, although I would never ask him for such a custom job.

**Comment by Stories8106** [comment]
Sorry I have one more quick question, have you confirmed someone (anyone) who has gotten it to work on a PG2v2?

I'll see if I can get an exchange for a sensitive stick, but my worry is that a new one will come in and have the same issue with the firmware.

**Comment by eduardofilo** [comment]
Well, since I don't have that console, I don't keep those details in my memory, but I would say yes, i.e. that other persons didn't have that problem. Although the concept that Ninoh told me that OD Beta is more sensitive in the neutral zone of the stick seems reasonable to me. In that case changing the stick might work. But the best thing would be to improve that calibration.

**Comment by eduardofilo** [comment]
@Stories8106 This commit in ODb seems related to your problem:
https://github.com/OpenDingux/linux/commit/083a38c8a7d73dfee95cdabdf2ce6b4d6f4cc2a5

It will be included in next Adam release.

**Comment by eduardofilo** [comment]
In the meantime, try installing the latest ODb update:

http://od.abstraction.se/opendingux/latest/gcw0-update-2021-12-12.opk
