### ISSUE TITLE
Battery indicator on RG280V shows empty

### ISSUE THREAD

**Issue by Rabobert** [eduardofilo/RG350_adam_image#254]
### What happened?

Also Apps show "RG350 test" instead of RG280V.

### Device

RG280V

### Version

v1.4.2

**Comment by neilswann80** [comment]
I'm running an RG280v on 1.4.2... my battery indicator is working perfectly, so possibly a hardware issue?

>Also Apps show "RG350 test" instead of RG280V.

Do you mean the button test app?  If so, that is normal.

**Comment by eduardofilo** [comment]
That application is only suitable for the RG350, that's why it's called that. Used on the RG280V it produces uncontrolled results such as the battery level. Just don't use it on RG280V. The image is common for several machines and there are things that go better or worse on some models.

**Comment by eduardofilo** [comment]
Correction. The problem of incorrect battery measurement is not because the application is designed for RG350. I have checked that on that machine it also indicates 0%. The application is compiled for stock system and ODbeta must have changed the hooks to get that information. I will try to locate an equivalent application that works well on ODbeta to replace it in a future revision of the image. I reopen the issue to keep this in mind.

**Comment by eduardofilo** [comment]
OK, I understand. The version installed in the image is 1.3d and in the repository I see that it is 1.4. I will include it after correcting the battery issue. I will think about removing the part that shows the frequency so that the question marks do not appear. Thank you.

**Comment by a-dekker** [comment]
Maybe we don't need to remove the cpu freq part. Just noticed we can read /sys/devices/system/cpu/cpu0/cpufreq/**scaling**_cur_freq instead of /sys/devices/system/cpu/cpu0/cpufreq/**cpuinfo**_cur_freq
Not 100% these values are always identical, but in my case they do match.

**Comment by eduardofilo** [comment]
Then we have all the pieces. Thank you very much @a-dekker.

**Comment by eduardofilo** [comment]
Done. I have already added to the repository the OPK version of `RG350 test` that includes the changes you proposed @a-dekker. It will be included in the next release. In the meantime you can install it manually by deleting the file `/media/data/apps/rg350test_v1.3d.opk` and placing [this one](https://github.com/eduardofilo/RG350_adam_image/raw/master/data/apps/rg350test.opk) in the same directory.
