### ISSUE TITLE
Mame not saving high scores to some games

### ISSUE THREAD

**Issue by BrickHardmeat** [eduardofilo/RG350_adam_image#269]
**Device** : RG280M
**Version**: 2.0

I installed version 2.0 on my new RG280M and downloaded the Mame 0.78 Rompack so I had the correct set.  Copied everything into the Arcade folder and also scraped them as well.

I've played "Bubble Bobble" a few times using the retroarch_rg350_mame2003.opk emulator and it loads and runs just fine, albeit with the copyright nag screen, but whenever I exit the game and re-load it, the high score always resets to the default.   It's also happened on a few random games as well.

I tried getting the Final Burn version of Bubble Bobble as well and place it into the "FB" folder and still had the same result - the high scores reset every time i loaded the game.

While I know a few Retroarch settings here and there, i'm wondering if it's something in that arena ?

**Comment by BrickHardmeat** [comment]
This is no longer relevant to me so I hope it's ok to close it.

**Comment by eduardofilo** [comment]
I don't know if there will be games that are particularly incompatible with high score recording, but I can confirm that the system works in some games. In addition from Adam 2.0 onwards they are recorded on the external card (in the directory `retroarch/saves/mame2003/hi`) so they are preserved between different installations of the image on the internal one.
