### ISSUE TITLE
autosave_interval=0 causes me to question my life decisions

### ISSUE THREAD

**Issue by anderbubble** [eduardofilo/RG350_adam_image#27]
While investigating #3 I discovered that this image sets `autosave_interval=0` in `retroarch.cfg`. I think this means "disabled." Particularly with how hangy / crashy RA has been on this image, this has caused me much frustration, as hangs mean I lose progress in a game I'm already dubious about playing. (/me shakes his head at how much time he's put into Crusader of Centy.)

I expect you disabled `autosave_interval` to reduce wear on the SD card; but just bumping it to `60` or `120` or even `300` would be better than disabling it, imo.

**Comment by eduardofilo** [comment]
Hi. Indeed this afternoon when I reset the configuration, that setting also caught my attention. Like the audio, it was like that from the beginning. Not only from the begining of Adam, but from begining of RA installer.
It is clear that the RA team changes its default settings from time to time, and by inheriting configurations you deviate from its recommendations. Surely the resetting of the configuration will come in handy for more things.
I will close the issue when publishing the next release with that and other changes included.

By the way, do you understand what autosaves this option? The menu says that saves the non-volatile SaveRAM. I have googled but read too fast. The only thing that I have seen clear is that would be better to increase to 60 at least as you suggest. I will do it.

Thanks for the info.

**Comment by anderbubble** [comment]
> do you understand what autosaves this option

I think you're asking what `autosave_interval` does. If so, this is my understanding:

When a game has battery-backed save ram (SRAM) that is just that: RAM. As such, by default, it is volatile, and isn't preserved from run to run. Retroarch detects the use of save ram and, at a minimum, saves it out to a file when RA closes content. It also detects these files and restores the contents of the save ram when the game starts. However, if RA crashes, your save ram may not be saved.

To protect against this, `autosave_interval` can save the SRAM to a file at regular intervals. I think every 10 seconds is the default; but it's reasonable that in an embedded platform like this, backed by an SD card, maybe every 10 seconds is too much. But 60 or 120 or even 300 seconds is still way better than "only if RA shuts down successfully."

**Comment by eduardofilo** [comment]
Understood. Thanks...

**Comment by eduardofilo** [comment]
Included in v1.2
