### ISSUE TITLE
About Chinese garbled code

### ISSUE THREAD

**Issue by zsl1127** [eduardofilo/RG350_adam_image#270]
Thank you for your efforts
Simplemen does not support Chinese character sets
Is it added in the later version?

**Comment by a-dekker** [comment]
See this very recent discussion https://github.com/eduardofilo/RG350_adam_image/discussions/256#discussioncomment-3078217

**Comment by eduardofilo** [comment]
The request should be made in the SimpleMenu repository. Or better yet solved by oneself as @a-dekker has done in the discussion he mentions you. Great job @a-dekker. I close the issue as it is being commented in Discussion #256.

**Comment by eduardofilo** [comment]
The request should be made in the SimpleMenu repository. Or better yet solved by oneself as @a-dekker has done in the discussion he mentions you. Great job @a-dekker. I close the issue as it is being commented in Discussion #256.
