### ISSUE TITLE
binterval wont go lower than 4 

### ISSUE THREAD

**Issue by user4244** [eduardofilo/RG350_adam_image#287]
### What happened?

hi, im using the controller overclock but when i change the rate to 1000 the binterval goes from 6 to 4 and wont go any lower. is there a fix for this?

### Device

GCW-Zero

### Version

v1.0

**Comment by user4244** [comment]
sorry i dont know what device or version i just picked the first 2

**Comment by eduardofilo** [comment]
I don't understand the question. What are you modifying?, do you mean the parameters inside the SimpleMenu config.ini file related to overclock?

I see you have closed the issue. Have you found a solution to your problem? I am interested to know what it was.
