### ISSUE TITLE
Blank screen on RG350P on fresh boot

### ISSUE THREAD

**Issue by FatehAK** [eduardofilo/RG350_adam_image#291]
### What happened?

Hi, I was trying to install the version 2.1 of Adam Image to my RG350P console. I flashed the SD card with Balena and ran the select_kernel.sh file in the terminal and selected RG350/P option. 

Now when I insert the SD card and try to boot the console, all I get is a blank screen. 

I found this thread on reddit [link](https://www.reddit.com/r/RG350/comments/sepg1e/rg350_boots_to_black_screen_with_adam_firmware/) that says to select the RG350M during select_kernel.sh. It seems to boot up when I use the RG350M kernel files, but the experience is glitchy all round and very laggy.

Could you please help checking why the kernel files of RG350 don't work for RG350P?

### Device

RG350P

### Version

v2.1

**Comment by eduardofilo** [comment]
When the wrong kernel model is selected between those two machine versions, what happens is:
* RG350/P kernel installed on RG350M: Blank screen
* RG350M kernel installed on RG350/P: Only the upper left quarter screen is visible.
So it looks like the factory installed the panel of an RG350M on your RG350P. This is not the first case I have seen.

**Comment by FatehAK** [comment]
ah I see, how to go about this then, is it impossible to have Adam image installed on my RG350P?

**Comment by eduardofilo** [comment]
I understand that using the RG350M kernel. You say you have a glitchy and laggy experience, so I understand that your panel will not be the conventional RG350M panel either. Sorry, but you seem to have a particular situation for which the rest of us can only speculate. One thing I can think of that you can do is buy a new official panel (either P or M type, I recommend the M) and replace it. But you have to be willing to bear the cost and the handling of the console for replacement. In short, it sounds like your console is not normal.

I have modified the screen of my RG350 two times as you can see here:
https://apuntes.eduardofilo.es/2020-07-12-rg350_screen_mod.html#instalacion-pantalla-oficial

**Comment by FatehAK** [comment]
I understand, thanks for the tip, will see if I can procure one.
