### ISSUE TITLE
select_kernel.sh should check that the copy actually succeeds

### ISSUE THREAD

**Issue by febs** [eduardofilo/RG350_adam_image#296]
### What happened?

I ran the script, which terminated with the successful message. 
The image didn't work though, and I realized that the copy of the files in the "rg280m" folder actually didn't happen for a permission error (my SD card was mounted so that only root could access it for some reason). 

running "cp" manually showed me that, so it was easy to solve, but... the bash script did return success while the script actually failed.

I suggest to make a check of the return status of the "cp" commands before returning success.

Thanks!

### Device

RG280M v1.1 (without HDMI)

### Version

v2.1

**Comment by eduardofilo** [comment]
Fixed in 81b3e833640b8f1db69371dae47dabe248690dc9.
