### ISSUE TITLE
ReGBA Screenshot discoloration 

### ISSUE THREAD

**Issue by Akmal02** [eduardofilo/RG350_adam_image#299]
### What happened?

Whenever I am on ReGBA and take screenshots using Power+X, the stored images have weird discoloration. Please see the attached images for a better look.
(Using Hardware (Scale2X) with bicubic interpolation)

![IMG_20220926_154444_630](https://user-images.githubusercontent.com/10498004/192221292-fbdd0da8-9f96-4aaa-a42c-979425564e9e.jpg)
![IMG_20220926_154446_612](https://user-images.githubusercontent.com/10498004/192221301-4568e611-9853-498c-91ea-aee41113574b.jpg)
![IMG_20220926_154443_561](https://user-images.githubusercontent.com/10498004/192221305-583186d0-bd58-45e5-9580-40fecdff834e.jpg)

Although on gameplay the screen looks fine. Tested on other GBA cores (RA-mGBA and RA-gpSP), but didn't encounter this issue. Only ReGBA.

Somebody else also found this issue [on Reddit](https://www.reddit.com/r/RG350/comments/ty1fkx/screenshots_in_regba_have_weird_colors_please/?utm_medium=android_app&utm_source=share) but it was 5 months ago and no possible solution was found yet for Adam Image.

### Device

RG300X

### Version

v2.1

**Comment by eduardofilo** [comment]
Surely the emulator does not correctly inform the system about the video mode used (surely the color encoding) and ODbeta's screenshot system gets confused, but I can't tell. Try to open an issue in the ReGBA repository. The one installed in Adam is https://github.com/jdgleaver/ReGBA/
