### ISSUE TITLE
No xmame support in gmenu2x.

### ISSUE THREAD

**Issue by nl255** [eduardofilo/RG350_adam_image#308]
### What happened?

When using gmenu2x instead of simple menu there is no way to load arcade games in xmame, the only options are the retroarch cores or FBA.

### Device

RG280V

### Version

v2.1

**Comment by eduardofilo** [comment]
Good point. I have built three OPK wrappers for launching xMAME in its three romset versions. It will be included in next release. In the meantime, you can install it manually copying the OPKs to `/media/data/apps`.

[xMAME_wrappers.zip](https://github.com/eduardofilo/RG350_adam_image/files/10188370/xMAME_wrappers.zip)
