### ISSUE TITLE
extending partition per instructions with diskgenius is not possible

### ISSUE THREAD

**Issue by dbastien** [eduardofilo/RG350_adam_image#309]
### What happened?

diskgenius reports freeinode number and free block numbers recorded in super block are incorrect when attempting to extend partition as per instructions.

### Device

RG280V

### Version

v2.1

**Comment by dbastien** [comment]
I did image with Balena Etcher as per documentation as well.

**Comment by eduardofilo** [comment]
I have tested twice by flashing with Balena Etcher from Windows and using the Linux `dd` command, both times expanding the partition with DiskGenius on Windows, and have had no errors of any kind. It has to be a particular problem with your card(s) or the adapter you use to mount them in the PC.

**Comment by eduardofilo** [comment]
I must say that I did the resizing of the partition as soon as I finished flashing, i.e. without having inserted the card in the console and booted with it.
