### ISSUE TITLE
Deleting last game in the list stops the device, requires reboot

### ISSUE THREAD

**Issue by psolovyov** [eduardofilo/RG350_adam_image#310]
### What happened?

I was working on deleting games from the catalog and went down to the bottom of the list. When deleting the last item in the list the device stalls and doesnt recover.

After reboot it starts working again. 

I did this in multiple consoles and now Neo Geo console folder does not work - device stalls when I try opening Neo Geo.

The SD card is Sandisk Extreme - not the original card from manufacturer.

### Device

RG280V

### Version

v2.1

**Comment by eduardofilo** [comment]
Sorry for the late reply. It's an old SimpleMenu issue. Until SimpleMenu code debugs that problem, the workaround is to delete the file that records the last session (`/media/data/local/home/.simplemenu/last_state.sav`). Starting the console while holding down the `B` key will automatically clear it, as described here:

https://github.com/eduardofilo/RG350_adam_image/wiki/En:-6.-Problem-solving#boot-loop-after-power-on

**Comment by a-dekker** [comment]
I noticed the simplemenu repo is merging PR's again after a long period of inactivity. @eduardofilo is your commit already addressing this https://github.com/fgl82/simplemenu/pull/207/commits/06943bb334930b69f3172d7ed0cfda3c8c60f1a1?

**Comment by eduardofilo** [comment]
Yes, it was part of the commits to add support for Miyoo Mini in SimpleMenu, but this workaround can serve for OpenDingux version also. It will be included in next Adam version. But before I want to debug the problem of restoring session function (when the last_state.sav is loaded) to try to give a more convenient solution and not this "using a sledgehammer to crack a nut" way of deleting that file.

**Comment by psolovyov** [comment]
> Sorry for the late reply. It's an old SimpleMenu issue. Until SimpleMenu code debugs that problem, the workaround is to delete the file that records the last session (`/media/data/local/home/.simplemenu/last_state.sav`). Starting the console while holding down the `B` key will automatically clear it, as described here:
> 
> https://github.com/eduardofilo/RG350_adam_image/wiki/En:-6.-Problem-solving#boot-loop-after-power-on

No worries! Thank you! Thank worked!
