### ISSUE TITLE
"dialog" package needed on linux

### ISSUE THREAD

**Issue by XargonWan** [eduardofilo/RG350_adam_image#328]
### What happened?

Select kernel bash script needs a "apt get install dialog" in Ubuntu 22.04, possibly in other distros/version too.

### Device

RG350M

### Version

v1.0

**Comment by eduardofilo** [comment]
A comment about the need for `dialog` has been introduced in the wiki:

https://github.com/eduardofilo/RG350_adam_image/wiki/En:-2.-Install-&-Upgrade#linux
