### ISSUE TITLE
Amiga and Commodore 64 games all crash

### ISSUE THREAD

**Issue by JazzJohannes** [eduardofilo/RG350_adam_image#329]
### What happened?

Amiga and Commodore 64 games all crash, despite having all the bios files in the right folder with the right names.

It loads them up, but then quickly shuts down, no matter which emulator I use or if I use overclocking or not.

### Device

RG350P

### Version

v2.1

**Comment by eduardofilo** [comment]
I don't know what to tell you, I can open games of those systems as you can see in the screenshots I attach. I have tested on both RG280V and RG350M. I recommend you to try with a clean install or with other ROMs.

![screenshot001](https://user-images.githubusercontent.com/2923728/222812938-bcf09baf-6c92-4301-a48c-c7eb8035f8e4.png)

![screenshot002](https://user-images.githubusercontent.com/2923728/222812976-34f83ada-8ef3-4205-a53f-bb03b57f7537.png)
