### ISSUE TITLE
Add Philips Videopac to Simple Menu and Rom Folder

### ISSUE THREAD

**Issue by Everett1954** [eduardofilo/RG350_adam_image#34]
Hi,
I noticed that o2rom.bin is a needed BIOS for ADAM 1.2. However there is no rom folder for the roms and it is not implemented in Simple Menu.

Can you make this a useable emulator for us to add roms to?

**Comment by eduardofilo** [comment]
Closed as it is the same issue as #28. Please, see coments there.
