### ISSUE TITLE
PyBackup no funciona

### ISSUE THREAD

**Issue by RicardoFAndres** [eduardofilo/RG350_adam_image#342]
### What happened?

He descargado hasta tres versiones diferentes de Adam y en todas obtengo el mismo error a la hora de ejecutar PyBackup.
Estoy intentando unir Adam y EVA, por si sirve de algo más.

Hago todo correctamente. Formateo SD, monto y quemo la imagen con Balena (he probado también con Rufus), ejecuto el bat y le digo la opción 3 (RG350/P), meto la SD en mi RG350P y cuando pulso en PyBackup (ya que EVA me pide cargar un sideload) me aparece el siguiente error. 

"**Destination directory not accesible. Review config file at: /media/data/local/.py_backup/config.ini**"

Esto lo he intentado con 3 tarjetas SD diferentes, Samsung, Kingston y Thosiba. De 32 las dos primeras y 8GB.
También he usado una SAMSUNG (y otras) para quemar y/o copiar EVA de diferentes maneras.

El resultado es el mismo en cualquier versión de ADAM o SD.

Al final he ido a ver el archivo config que me pide PyBackup pero veo que no se encuentra ahí tal y como dice sino en Destination directory not accesible. Review config file at: /media/data/local/home/.py_backup/config.ini. Aún así no se qué me está contando. Dejo foto adjunta.

¿Sabrías decirme a qué se debe? Como apunte final, aunque meta todo el contenido de EVA en la SD2, el sistema Adam no reconoce ninguna consola/rom. Cuando le doy a juegos solo sale Retroarch.

![Imagen de WhatsApp 2023-02-22 a las 13 18 17](https://user-images.githubusercontent.com/12787923/220617821-6bf9a032-6a86-4bbd-8efd-54aad986bb68.jpg)

### Device

RG350P

### Version

v2.1

**Comment by eduardofilo** [comment]
El mensaje indicaba un error en el directorio parametrizado en `destination_directory`, es decir en la SD externa, no la interna. El problema con las ROMs también parece indicar que algo no va bien en esa SD.
