### ISSUE TITLE
FBA and NeoGeo ROMs distorted screen on RG350M

### ISSUE THREAD

**Issue by Medard22** [eduardofilo/RG350_adam_image#37]
Hello, I recently upgraded my RG350M to Adam. I noticed that all NeoGeo ROMS are unplayable in FBA. The game runs, the sound and music work OK, but the screen is completely distorted.
![metalsl](https://user-images.githubusercontent.com/42897361/134965564-17c9a917-391b-4b78-aa45-7a995181c47d.jpg)
This is a screenshot of Metal Slug.  I tried to run FBA via it´s opk to try different settings, but I couldn´t fix it. 
I tried to replace the original FBA opk with this one - https://github.com/citral23/fba-sdl/releases   no luck.

CPS ROMs work perfectly fine.

**Comment by eduardofilo** [comment]
Hi. You are right. The problem is consistent combining RG350M screen (I gess that also in RG300X) with FBA standalone. I have commented the fix in [FAQ number 5](https://github.com/eduardofilo/RG350_adam_image#faq).
Thanks for reporting this.
