### ISSUE TITLE
Lower master volume

### ISSUE THREAD

**Issue by falkenhawk** [eduardofilo/RG350_adam_image#40]
Hi,
Could you perhaps give a hint how to change the master system volume, please?
I know I can lower the volume in retroarch config (I set it to -20 dB), but there are also other standalone emulators and games, which I find way too loud on the lowest volume level.
Rogue CFW has an alsasound config app, if I am not mistaken, perhaps we could have something similar in your fw? Or maybe it can be already configured manually in a config file, using Commander app? 🤔

**Comment by eduardofilo** [comment]
Hi.
Could you please give a concrete example for me to try?

**Comment by eduardofilo** [comment]
In new 1.3 release of the image, you have access to alsamixer in `Apps` section of SimpleMenu and in `settings` section of GMenu2X. I hope it helps.

**Comment by ridsama** [comment]
Is there any documentation on how to use alsasound utility? It doesn't seem to change my overall sound volume even with -20dB for everything. And also it resets after a reboot.

**Comment by danielristic** [comment]
The alsamixer does work and retain settings but it seems that even at -30dB it's still a bit loud on the RG280V.

**Comment by eduardofilo** [comment]
I understand. Unfortunately, I can only play with the options available in the programs and the system. Adjusting the correspondence of a certain value in alsamixer with the perceived volume is something that can only be adjusted by modifying the system.

**Comment by danielristic** [comment]
What's weird is that leaving the alsamixer value to the default setting and adjusting retroarch's audio gain value to -20dB seems to produce a sound that is much quieter compared to the system-wide -30dB value.

**Comment by eduardofilo** [comment]
Good workaround. That had not occurred to me. I will include it in the FAQ. Thanks.

**Comment by eduardofilo** [comment]
I see now that @falkenhawk already suggested it in first comment.

**Comment by eduardofilo** [comment]
> What's weird is that leaving the alsamixer value to the default setting and adjusting retroarch's audio gain value to -20dB seems to produce a sound that is much quieter compared to the system-wide -30dB value.

Well, I understand that the -20dB in RA is accumulated over the PCM level. So, you have to put PCM to 0dB to compare RA output adjusting with alsamixer. I have compared the following:

* RA: 0dB; PCM/alsamixer: -30dB
* RA: -30dB; PCM/alsamixer: 0dB

and they sound similar to me.

**Comment by eduardofilo** [comment]
This topic in FAQ. I hope it helps:

https://github.com/eduardofilo/RG350_adam_image/blob/master/README.md#q7-how-can-i-lower-the-minimum-volume-without-actually-muting-the-sound-the-minimum-is-still-very-high

**Comment by danielristic** [comment]
> Well, I understand that the -20dB in RA is accumulated over the PCM level. So, you have to put PCM to 0dB to compare RA output adjusting with alsamixer. I have compared the following:
> 
> * RA: 0dB; PCM/alsamixer: -30dB
> * RA: -30dB; PCM/alsamixer: 0dB
> 
> and they sound similar to me.

Thanks for your answer, I got confused and did not realise that the PCM levels in alsamixer also changed when using the volume buttons (I thought it was an independent setting).

The FAQ is really clear and it works well, thanks!

**Comment by falkenhawk** [comment]
> I see now that @falkenhawk already suggested it in first comment.

yes, that works fine, but outside of RetroArch i can't find a way to lower the volume below pcm level 32 (-30dB), for example in Gambatte emulator.

**Comment by falkenhawk** [comment]
But why do I even bother running gambatte directly, as retroarch's core is also based on Gambatte, you may ask. I noticed that the performance of standalone's gambatte was better than retroarch's, but it turned out it was because of the default settings in retroarch - there is "color correction" enabled and set to "accurate". That makes the colors look much closer to how they look on original gbc, which is very nice. But it also causes audio (esp. music) to stutter in some games, i.a. Tomb Raider. When color correction is disabled or set to "fast" then sound is fine, but colors are not that nice anymore. (they are darker and more saturated, which one may think that's better, but they are not how they were supposed to look on gbc.)
Is rg280v not powerful enough to run without audio issues with accurate color correction enabled? 🤔
