### ISSUE TITLE
Music player

### ISSUE THREAD

**Issue by retrogamecorps** [eduardofilo/RG350_adam_image#41]
Hi Eduardo,

I'm seeing several requests for a music player with the Adam image.  Does GMU (or similar) work on OD Beta, and if so, could it be added to the Applications section?

**Comment by eduardofilo** [comment]
I have tried, but my skills compiling C projects are novice level.
What I have tried:

* Run [this OPK](https://github.com/SeongGino/RetroGame350-AppRepo/raw/master/Applications/gmu-0.10.1-gcw0.opk). Result: `bus error`.
* Compile [this repository](https://github.com/JORGETECH/gmu) with OD Beta toolchain. Result: `bus error`.
* Run [this OPK](https://github.com/retrogamehandheld/OpenDingux/raw/master/Applications/Oldplay.opk). Result: It opens, but crash with MP3 and hangs with WAV.
* Compile [this repository](https://github.com/jhe2/gmu). Result: I am not able to compile it.

I keep the issue open in case we find an alternative in the future.

**Comment by retrogamecorps** [comment]
I really appreciate you trying, your level of effort is far beyond what I was hoping.  I hope an alternative comes available soon!

**Comment by subatomicglue** [comment]
Any chance to add oldplayer as well?

**Comment by subatomicglue** [comment]
I've taken the liberty of testing, and oldplayer works!
You can find the OPK from here, 

https://github.com/SeongGino/RetroGame350-AppRepo/tree/master/Applications

I just dropped it into my /media/sdcard/APPS directory, it shows up under APPLICATIONS category under Adam.

**Comment by eduardofilo** [comment]
I think that I tested it also (oldplay) and give problems to me, but I don't remember well.
I'll give it a chance again and see what I do.

**Comment by subatomicglue** [comment]
I wonder if it can be recompiled, looks like 2013-2014 was when it was created.  Maybe the OS has updated dependencies by now.

I also wonder if there are logs in the system that could tell us why it is crashing.  Maybe mp3 shared lib isn't found or something.

Can we run an OPK from ssh?  Then we would see the error on the command line...

(I know Mac/Linux, but not opendingux/rg350)

**Comment by eduardofilo** [comment]
Yes, compile it will be one of the things that I will try.
You can enable logs in GMenu2X options and the see them in Log Viewer (that shows up in `settings` section when log is enabled).
You can run an opk from SSH with `opkrun` command. When doing that, you have to open the `Terminal` application in GMenu2X.

**Comment by eduardofilo** [comment]
Solved in release v1.4.

**Comment by felixmreeve** [comment]
Hello @eduardofilo I was wondering whether there is a reason that ffplay is not included in Adam Image? It comes with the original firmware but I haven't been able to get a working opk on the device after installing Adam. Is there something I'm missing? I'm looking to play mp4 files. Thank you

**Comment by eduardofilo** [comment]
Hello.
@a-dekker built it. You can see the conversation in discussion #233.
