### ISSUE TITLE
FBA scaling issue on RG350M fixed upstream

### ISSUE THREAD

**Issue by Medard22** [eduardofilo/RG350_adam_image#52]
Hello @eduardofilo I found out that the FBA scaling bug that affected RG350M in NeoGeo games has been fixed by the @plrguez couple of days ago. I tested the latest opk on my device and it works perfectly fine, even with HW scaling on. Thank you for all your hard work. 

https://github.com/plrguez/fba-sdl/releases

**Comment by eduardofilo** [comment]
Solved in release v1.4.
