### ISSUE TITLE
Pull request submitted for new Cheatsheet 1.3 and READMEs

### ISSUE THREAD

**Issue by iammeat** [eduardofilo/RG350_adam_image#57]
Hi Eduardo,

I updated my Cheatsheet for the new BeebEm changes and the other updates for the list, and submitted a pull request.  Let me know if I missed anything.

**Comment by eduardofilo** [comment]
Thank you @iammeat .
I did not notify you when I did the release because I did not want to commit to having to update the cheatsheet. In future versions I will try to prepare the changes in the list of controls so that you do not have to check them one by one.
I will review the PR tomorrow (I hope).
Thank you very much.

**Comment by iammeat** [comment]
No, don't do extra work for that.  I don't mind checking the documentation commits.  You've got enough to handle with maintaining the image.

**Comment by eduardofilo** [comment]
OK. I have merged the PR.
I have found these little details:

* Lack of Famicom Disk System controls.
* The label `FBA (MAME, FBA y CPS)` say `y` instead `and`.
* Lack of FBA controls. Perhaps those of insert coins or the start player can be presumed.
* In PocketSNES is `Select + Start or Power` like ReGBA, for instance.

Thanks.

**Comment by iammeat** [comment]
Yeah, cool.  I'll update these tomorrow and submit another PR.

**Comment by iammeat** [comment]
Yeah, cool.  I'll update these tomorrow and submit another PR.

**Comment by eduardofilo** [comment]
Hi @iammeat I have added a new control at OpenDingux context. The last one that says:

|Select (while powering on)|Boot mode. Check [this guide](https://boards.dingoonity.org/retrominirs-90/a-quick-guide-to-flashing-opendingux-on-the-rs-90-using-windows-10-x64/msg186557/#msg186557)|
