### ISSUE TITLE
PocketGo 2 v2 battery drain when shut down

### ISSUE THREAD

**Issue by pfroo40** [eduardofilo/RG350_adam_image#64]
Running Adam image 1.3, my battery drains when the console is in "shutdown" mode. I've verified it is at 100% charge, shut it down from simplemenu, disconnected from power, and a few hours later I'll try and use the console but the battery is dead.

**Comment by eduardofilo** [comment]
Same situation like issue #63 . Try with a clean installation of OD beta and tell me if the situation changes. Although I have to say that in this case, the problem could be your battery. So try also with stock firmware.

**Comment by eduardofilo** [comment]
I close the case because of its age and because it is probably a particular problem.
