### ISSUE TITLE
GCW-Zero Compatibility

### ISSUE THREAD

**Issue by Tabaluga** [eduardofilo/RG350_adam_image#65]
Dear @eduardofilo ,
thanks for your great effort in making this image.
I'm a proud user of the GCW-Zero and I try to keep it up to date to use it as good as possible.
For me, it's a tremendous job to find the right repository or the right apps which are still working with the GCW-Zero, and it would mean a lot if I could use your image with the GCW-Zero, so I want to ask if your image is compatible with the GCW-Zero? Or parts of it? Or can I use only the apps from this image?
Thanks for your help.
Best regards

**Comment by eduardofilo** [comment]
Hello. Thank you for your comments.
From what I know after studying the ODbeta installation script, the difference with GCW-Zero is that it uses a different bootloader than the Anbernic consoles. Therefore, it would be possible to adapt the image by flashing the corresponding bootloader in the first sectors of the card. Then you would also have to append the device tree corresponding to your machine at the end of the kernel.

I am going to try to prepare a version for your console and if you do me the favor of testing it a bit, I will add it to the list of supported consoles in the image.

**Comment by eduardofilo** [comment]
Try this please:

https://drive.google.com/file/d/13sBRJXmbbMOIp9wxUg2L5Li7dcq40mms/view?usp=sharing

It should run directly, without the need of using kernel selection script like in main image.

**Comment by Tabaluga** [comment]
Dear @eduardofilo ,

that's like christmas for me in this hard and turbulent time - I can't thank you enough for your efforts - to resurrect my old GCW-Zero with the latest versions of the well-known emulators and new systems thanks to RetroArch, this is a real game changer for me and I look forward into the future.

---

## 1. Notes

I have two very important differences in the GCW-Zero, compared to the following:

### 1.1 Internal and External Storage

The GCW-Zero has, like all its successors, two SD cards that act as *internal and external storage* (see [specification](http://www.gcw-zero.com/specifications)), but with the GCW-Zero you can *only* exchange the external storage (see [media](http://www.gcw-zero)), not the internal storage.

To update the operating system of the GCW-Zero you use an [Update-Application](http://www.gcw-zero.com/updates#instructions), which updates the internal storage which you can not exchange it.

> Is an Update-Application or a script possible to copy and update the Adam-image in the internal storage?

### 1.2 Hardware buttons

At the GCW-Zero the hardware keys `X` and `Y` are interchanged (see [media](http://www.gcw-zero.com/media)).

> I do not know whether this is a mistake in design. I can open my GCW-Zero and exchange the buttons so everything fits.

Furthermore, the following hardware buttons are not available: `L2`, `R2` and `right analog stick` (see [media](http://www.gcw-zero.com/media)).

> Perhaps some defined [controls and shortcuts](https://github.com/eduardofilo/RG350_adam_image#controls) must be redefined.

---

Based on the fact that I can not access the internal storage of the GCW-Zero directly to copy the Adam-image into the *internal storage*, I would nevertheless like to continue testing the Adam-image and give you a feedback - at least the apps and emulators should work.

Do not hesitate to ask if you need more information, logs or more details, and I help where I can.

## 2. test environment

To test the Adam-image I created a clean *test environment*:

1. I have updated the operating system to the latest [OpenDingux beta](http://od.abstraction.se/opendingux/latest) version of @pcercuei :
   - kernel: 5.15.0-rc6-opendingux
   - root fs: g9306b6bda9
   - compiled: 2021-11-25
   - file: `gcw0-update-2021-11-25.opk`

2. I have deleted all settings from all apps, emulators and games:
   - `/media/data/local/home/*` and
   - `/media/data/local/share/*`

### 2.1 Adam-image

I installed the Adam-image after the [fresh installation guide](https://github.com/eduardofilo/RG350_adam_image#fresh installation), but as already described above I do not know how to copy the Adam-image into the internal storage.

> Idea: A *Update-Application* to copy the Adam-image to the internal storage.

### 2.2 Contents

Since I can only access one external SD card at the GCW-Zero, I used the same SD card, and prepared on the second partition all the contents according to the instructions for the [directories](https://github.com/eduardofilo/RG350_adam_image/blob/master/images/sdcard_paths.png), [BIOS](https://github.com/eduardofilo/RG350_adam_image#bios) and [games](https://github.com/eduardofilo/RG350_adam_image#roms).

My directory structure:

```bash
/-- apps
|-- backups
|-- bios
|-- cheats
|   `-- PlayStation
|-- dev
|-- OpenBOR
|-- roms
|   |-- 32X
|   |   `-- .previews 
|   |-- ...
|   `-- ZX
|       `-- .previews 
|-- root
|-- mininit-syspart
|-- mininit-syspart.sha1
|-- modules.squashfs
|-- modules.squashfs.sha1
|-- rootfs.squashfs
|-- rootfs.squashfs.sha1
|-- uzImage.bin
`-- uzImage.bin.sha1
```

## 3. Adam-image test

Based on my environment, I tested the apps, emulators and RetroArch:

1. Apps > SimpleMenu: changing between sections does not work; no games are displayed
2. Emulators > ColecoVision: works
3. Emulators > IntelliVision: exec.bin not found; works after creating symlink to bios files
4. Emulators > Nintendo GBA: works; external bios found after creating symlink to bios file
5. Emulators > PICO-8: works
6. Emulators > PlayStation: external bios found after creating symlink to bios file; black screen; perhaps some files in $home are missing
7. Emulators > RetroArch: no cores found
8. Emulators > ScummVM: Failed loading symbol PLUGIN_getVersion from plugin /opk/libmad.so; failed loading PLUGIN_getVersion; unable to resolve symbol
9. Emulators > SNES: works
10. Emulators > VirtualBoy: can't load rom; could not load rom in storage
11. RetroArch > no matter which core I start, it terminates immediately; the logfile (Settings > Log Viewer) is empty

## 4. Summary

I think most problems are solved by themselves as soon as the Adam-image is in the internal storage and the external SD card can be used as EXT for the contents as intended.

best regards

**Comment by borderomm** [comment]
@eduardofilo I just saw this open issue by chance 5min ago. This is amazing!
I also own a GCW-ZERO and I just flashed a new sdcard with your image and inserted it in the device (INT card).
I took my EXT card from the RG280v and.... BOOM! After so many years my GCW-ZERO is back to life like new!!!

I only tested a handful of games but so far so good.
I haven't tested keys yet. I wanted to quickly share feedback so have only spent 3min playing a couple of Game Boy and PICO-8 games.

Super cool!

Oh and volume and brightness works :+1:

**Comment by borderomm** [comment]
@Tabaluga You can open the GCW-ZERO and access the sdcard without any issues. Just remove the white rubber feet and you'll have access to the 4 screws holding the back plate.
Just be careful when lifting the back plate as the cables may not give you much room to manouver.
The card should be black, maybe it has a plastic foil on top to protect the heat but with some small tweezers you can get access to it.

For me it was easy as once i replaced the buttons and enlarged the battery cables

**Comment by eduardofilo** [comment]
@Tabaluga I have a RG350 (first model) and like the GCW-Zero, I have to open the unit. At the moment there is no other way to install the image. I have to study other possibilities of uploading the image by USB, but I need time to analyze it and currently my free time has been reduced considerably.

@borderomm OK, thanks for the test. Seeing this, I will include GCW0 as supported in next Adam revision. I leave this issue open until then.

**Comment by eduardofilo** [comment]
Could you please try this version of the image? I am going to incorporate the support for GCW-Zero in the special version of Adam that is released for PG2v1 since they share bootloader, so I have added the kernel of the last one and the pair of scripts to select between both models in a similar way to how it is done with the different Anbernic models in the normal image. As I do it blindly, I would like to know if after the changes, the image starts on your machine.

https://drive.google.com/file/d/1X3Okjh9RcOJyx5YlM6n26Oz7HTGeCAVm/view?usp=sharing

**Comment by Tabaluga** [comment]
Dear @eduardofilo ,

please excuse my late response. The last days before Christmas were professionally very strenuous for me and associated with many overtimes so that I had very little free time.

Since yesterday, I finally have vacation and can devote myself to the upgrade.

I opened up my GCW-Zero as instructed by @borderomm  and flashed the internal SD-Card with the latest `adam_v1.4b_PGv1.img.xz` image, which works as expected, and I'm more happy than ever, that you brought back life to my old GCW-Zero.

Currently, I'm preparing one system after another and testing every emulator. If I found issues or have ideas for enhancements, I'll gladly post them.

Thanks again for your hard effort and continuing support to keep these handhelds alive.

Best regards and happy holidays

**Comment by eduardofilo** [comment]
Great. In that case I will incorporate the official support to GCW-Zero in the next version of the image. Thank you very much for taking the time to test it.

**Comment by eduardofilo** [comment]
Solved in release v1.4.

**Comment by eduardofilo** [comment]
Hi. On issue #262 I am having trouble determining if the image build system still produces a valid result for GCW-Zero and PocketGo2v1. Could you please test this preliminary version of the image to see if it works on your machines? Remember to run the kernel selection script after flashing the card. Thank you.

https://drive.google.com/file/d/1FW3rlCHbDK7WvBrdoxSdlyav7siNH0mT/view?usp=sharing

**Comment by paletochen** [comment]
Hey @eduardofilo 
Unfortunately I am on vacations these days so have no access to the GCW-Zero when I am (different country).
I would not be able to try it until August and I believe it may be a bit too late for your needs
Sorry :(

**Comment by borderomm** [comment]
Hey @eduardofilo
Unfortunately I am on vacations these days so have no access to the GCW-Zero when I am (different country).
I would not be able to try it until August and I believe it may be a bit too late for your needs
Sorry :(

**Comment by ValdikSS** [comment]
The version 2.1 works on GCW Zero without any major issues.

Since you're not able to flash internal MicroSD card without disassembling, here's my how-to. Feel free to add it in wiki.

# How to flash Adam Image on GCW Zero

You need Linux for that.

1. Download latest [PGv1 Release Image](https://github.com/eduardofilo/RG350_adam_image/releases)
2. Unpack xz: `xz -d adam_v2.1_PGv1.img.xz`, you'll have `adam_v2.1_PGv1.img` in the same directory
3. Split image into MBR, bootloader, system partition, data partition:
    - `dd if=adam_v2.1_PGv1.img bs=512 count=1 of=mbr.bin`
    - `dd if=adam_v2.1_PGv1.img bs=512 skip=1 count=30 of=bootloader.bin`
    - `sudo losetup --show -Pf adam_v2.1_PGv1.img`
    - `mkdir m && mount /dev/loopXp1 m`, where `X` is the device number from the previous `losetup` step
    - `sudo mv m/gcw0/* m/` - this will copy gcw0 kernel to the root of system partition
    - `sudo umount m && sync`
    - `sudo cat /dev/loopXp1 > system.bin`, where `X` is the device number from the previous `losetup` step
    - `sudo cat /dev/loopXp2 > data.bin`, where `X` is the device number from the `losetup` step
    - `sudo losetup -d /dev/loopX`, where `X` is the device number from the `losetup` step
4. Git clone [Ingenic-boot](https://github.com/gcwnow/ingenic-boot)
5. Apply the following patch or it won't compile:  
```diff
diff --git a/source/stage2_cmd_tool/stage2.h b/source/stage2_cmd_tool/stage2.h
index 54e6ce6..52b9caa 100644
--- a/source/stage2_cmd_tool/stage2.h
+++ b/source/stage2_cmd_tool/stage2.h
@@ -148,4 +148,11 @@ enum OPTION
 
 /*-------------------------------------------------------------------------*/
 
+int sd_card_init(struct ingenic_dev *ingenic_dev);
+
+int sd_card_program(struct ingenic_dev *ingenic_dev, unsigned int addr,
+                    const char *file_path, int check);
+
+int usb_ingenic_nand_ops(struct ingenic_dev *ingenic_dev, int ops);
+
 #endif /*__STAGE2_CMD_TOOL_H__ */
```
6. `make`
7. Press SELECT+POWER on the GCW Zero
8. Connect GCW Zero to the PC via USB
9. Run `sudo ./ingenic-boot --mbr mbr.bin --boot bootloader.bin --system system.bin --data data.bin`

It takes quite some time (around 15 minutes). New firmware would be booted automatically.
