### ISSUE TITLE
PocketGo 2 v1 freezes at "Setup permissions..." at boot

### ISSUE THREAD

**Issue by JayCanuck** [eduardofilo/RG350_adam_image#68]
I was flashing all my old devices to the Adam Image as I really enjoy what it did to my RG280M and wanted to set them up before putting the old devices on the shelf.  The RG350 devices worked great with no issue, but my PlayGo (PocketGo2 v1) appears to always freeze at boot, with a full progressbar with the text saying "Setup permissions...".

Obviously an old device so I don't want to make a big deal out of it, but figured worth posting an issue for other who may encounter it (or if anyone is aware of a workaround, equally good).

**Comment by eduardofilo** [comment]
I don't have that device, so I need help to find the root of the problem. I refer to you to issue #7 that centers the investigation of the particularities of this device. Ask there to see if your mates with that device experiences your issue or they can help to find the reason.
