### ISSUE TITLE
Retroatchivments 

### ISSUE THREAD

**Issue by arthur-mts** [eduardofilo/RG350_adam_image#69]
Hello! Does adam image supports RetroArch Retroatchivments on RG350 (with a external wifi dongle of course)

**Comment by eduardofilo** [comment]
Hi.
Well, it is RetroArch the one that doesn't support Retroachievements on its OpenDingux version. Ninoh-FOX compiled a version with Retroachievements enabled for OpenDingux, but he attached to a Discord channel, so I can't point you to a public download link.

**Comment by arthur-mts** [comment]
can you send me a link for this discord server? i will really like to have Retroachievements on my RG350

**Comment by eduardofilo** [comment]
I think it is this: https://discord.gg/wurh4WM

Once inside, the channel where Ninoh-FOX uploaded the file is `Device Releases > od-stock`.
The file was uploaded at 2021-09-21 19:01 (CET or GMT+1).
