### ISSUE TITLE
PlayGo v2

### ISSUE THREAD

**Issue by DenZ-666** [eduardofilo/RG350_adam_image#70]
I have a PlayGo with a reset button. analogue of New PocketGo 2.
The firmware will not start if the battery is fully charged.  Checked on the image 1.3.1.
in the rg350test application it says that the battery is 0%.  By the way, the update of the open beta will fix the stick.

**Comment by DenZ-666** [comment]
I download video.
https://youtu.be/pBh1JjMhR3U

**Comment by eduardofilo** [comment]
Since we talked on Discord with the user S1eepy and with you, we should try to isolate the problem. For example try to test with a clean install of ODbeta to rule out that it is not a configuration issue in Adam.

**Comment by DenZ-666** [comment]
I confirm. This is an OpenBeta problem. Installed a clean image from pg350. Then I updated the open beta from 2021-11-25, the problem remained.

**Comment by eduardofilo** [comment]
Thanks for taking the time to make the test.
