### ISSUE TITLE
My Wi-Fi toggle stop working

### ISSUE THREAD

**Issue by rromney1** [eduardofilo/RG350_adam_image#73]
I have the original RG350. I love the Adam image it works way better than the original stock image but I can't get the Wi-Fi dongle to work on it. The Adam image it will would work for one sec and stop but when I put the original SD with the stock image it works fine is any suggestions?

**Comment by eduardofilo** [comment]
There are differences in the support of different Wifi dongles between stock and the ODbeta used in Adam.

In stock the supported ones were:

* Realtek RTL8188EU 150Mb/s (stock and ROGUE)
* Realtek RTL8188FU 150Mb/s (only ROGUE)
* Realtek RTL8192CU 300Mb/s (stock and ROGUE)

And in ODbeta:

* Realtek RTL8192CU
* Mediatek MT7601U

So, surely your dongle is based in RTL8188. The main developer of ODbeta commented that the RTL8188 chip is not supported in the latest versions of the Linux kernel, so he cannot integrate its support. You will have to find a supported dongle. I'm sorry.
