### ISSUE TITLE
Thoughts on switching the led to red when the battery goes bellow X percent

### ISSUE THREAD

**Issue by Sichroteph** [eduardofilo/RG350_adam_image#74]
Simplemenu is great for launching a game at boot. However when the emulation app is not retroarch, we loose track on the battery state.

Do you know if we can trigger the led color with a linux command so a simple background script could do the trick ? I know how to retrieve the battery percentage into the filesystem.
It can be another notification like the vibration motor.

If there are no easy way to do this, should I look into Paul Ceucueil code (his shortcut deamons seems quite deep into the system) or directly into the open dingux kernel ? 

I am mainly playing on reGBA, another idea would be to add this info into its system screen.

**Comment by Sichroteph** [comment]
Removed for future research

**Comment by eduardofilo** [comment]
Sorry, but I haven't studied the system so deeply. I compile everything that I am reading and I do not remember something related to the management of the LED. I thought the LED would start flashing when the battery was low. At least stock did. As I hardly play with the console and I have it almost always connected to the computer to access the terminal by SSH, I have not been able to see if ODbeta does the same, but I am almost sure that it does. Doesn't it?

**Comment by Sichroteph** [comment]
Thanks for your answer. I am not sure either, maybe that is a feature that has been lost with open dingux updates. I am doing some tests on a Rogue image - kernel 3.12.75-dingux+ and went to arount 20% without led flashing. Maybe I should go lower to be sure.

**Comment by eduardofilo** [comment]
Well, the same battery charging level (the real physical one) can be interpreted differently in ROGUE than in ODbeta, so the test would have to be taken beyond, yes.
